#!/usr/bin/bash

tmpdir=$(mktemp -d /tmp/libreoffice-XXXXX)
libreoffice --headless --convert-to "${2##*.}" --outdir $tmpdir "$1"
if [ -f $tmpdir/* ]; then
    mv $tmpdir/* "$2"
    rm -rf $tmpdir
else
    rm -rf $tmpdir
    exit 1
fi
